### ISSUE TITLE
Window-frame margin issue with gtk 3 dialogs

### ISSUE THREAD

**Issue by stevenhoneyman** [jpfleury/clearlooks-phenix#3]
Environment: openbox, compton, GTK 3.12, clearlooks-phenix 5.0.6
Problem (first dialog here):

![2014-09-28_t132549_746x209_scrot](https://cloud.githubusercontent.com/assets/7693796/4434230/10c96948-470b-11e4-8ad3-95017ee4bee3.png)

Workaround:
To get the result shown in the middle dialog above, here's what my settings looked like:
```css
.window-frame {
	border-width: 0px;
	border-radius: 7px 7px 0 0;
	border-style: solid;
	margin: 0px;
}
```

To get the 3rd dialog (rounded corners don't match anything else on my themes):
```css
.window-frame {
	border-width: 0px;
	border-radius: 0;
	border-style: solid;
	margin: 0px;
}
```
