### ISSUE TITLE
Gtk-WARNING: Not using units is deprecated.

### ISSUE THREAD

**Issue by paride** [jpfleury/clearlooks-phenix#37]
Every now and then I get this message:

```
Gtk-WARNING **: Theme parsing error: gtk-widgets.css:1214:18: Not using units is deprecated. Assuming 'px'.
```

The problem seems to be the `border-width` set to `1` instead of `1px`, here:

```css
combobox > .linked > button.combo:disabled:last-child {
        border-image-width: 3px 3px 4px 0;
        border-radius: 0 3px 3px 0;
        border-width: 0 1;
}
```

Should be trivial to fix.
