### ISSUE TITLE
GtkScale slider is painted outside of container (GTK 3.22)

### ISSUE THREAD

**Issue by trancexpress** [jpfleury/clearlooks-phenix#51]
Here is an inspection of a `GtkContainer` with a `GtkScale`:

![gtk322_scale_slider_image](https://user-images.githubusercontent.com/24752155/39477481-b622fd74-4d5f-11e8-8c59-b1816975491e.png)

This is more pronounced in Eclipse SWT, where anything outside of the container is not painted:

![gtk322_scale_in_swt](https://user-images.githubusercontent.com/24752155/39477599-00be3a4c-4d60-11e8-862f-25b583f69d43.png)

The following seems to fix the problem:

```css
diff --git a/src/clearlooks-phenix-theme-7.0.1/gtk-3.0/gtk-widgets.css b/src/clearlooks-phenix-theme-7.0.1/gtk-3.0/gtk-widgets.css
index 09c9159..89d9e58 100644
--- a/src/clearlooks-phenix-theme-7.0.1/gtk-3.0/gtk-widgets.css
+++ b/src/clearlooks-phenix-theme-7.0.1/gtk-3.0/gtk-widgets.css
@@ -384,14 +384,10 @@ row:selected:focus progressbar trough {
  * GtkScale *
  ************/
 
-scale.vertical {
-    min-width: 10px;
-    padding: 3px 5px;
-}
-
-scale.horizontal {
-    min-height: 10px;
-    padding: 5px 2px;
+scale {
+  min-height: 13px;
+  min-width: 21px;
+  padding: 12px;
 }
 
 scale.horizontal slider,
```

**Comment by trancexpress** [comment]
I'll try out some other changes to the theme and will post my findings.

**Comment by trancexpress** [comment]
Here is what I arrived at:

```css
diff --git a/src/clearlooks-phenix-theme-7.0.1/gtk-3.0/gtk-widgets.css b/src/clearlooks-phenix-theme-7.0.1/gtk-3.0/gtk-widgets.css
index 09c9159..030bd14 100644
--- a/src/clearlooks-phenix-theme-7.0.1/gtk-3.0/gtk-widgets.css
+++ b/src/clearlooks-phenix-theme-7.0.1/gtk-3.0/gtk-widgets.css
@@ -386,12 +386,12 @@ row:selected:focus progressbar trough {
 
 scale.vertical {
     min-width: 10px;
-    padding: 3px 5px;
+    padding: 9px 5px;
 }
 
 scale.horizontal {
     min-height: 10px;
-    padding: 5px 2px;
+    padding: 5px 9px;
 }
 
 scale.horizontal slider,
```

Before:

![padding_as_is](https://user-images.githubusercontent.com/24752155/39478421-b2c01bd2-4d62-11e8-8c29-9953a0d1eadf.png)

After:

![padding_9x](https://user-images.githubusercontent.com/24752155/39478435-b7d46f06-4d62-11e8-9426-0e3298c9b94a.png)
